{% set name = "datadog" %}
{% set version = "0.52.1" %}
{% set sha256 = "44c6deb563c4522dba206fba2e2bb93d3b04113c40191851ba3a241d82b5fd0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dog = datadog.dogshell:main
    - dogwrap = datadog.dogshell.wrap:main
    - dogshell = datadog.dogshell:main
    - dogshellwrap = datadog.dogshell.wrap:main
  skip: true  # [py<27]

requirements:
  host:
    - python
    - pip
    - hatchling >=0.15.0
  run:
    - python
    - requests >=2.6.0
    - typing  # [py<35]
    - configparser <5  # [py<30]

test:
  imports:
    - datadog
    - datadog.dogshell
  requires:
    - pip
  commands:
    - pip check
    - dog --help
    - dogwrap --help

about:
  home: https://github.com/DataDog/datadogpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Datadog Python library
  description: |
    The Python integration enables you to monitor any custom metric by instrumenting a few lines of code.
  doc_url: https://docs.datadoghq.com/integrations/python/
  dev_url: https://github.com/DataDog/datadogpy

extra:
  recipe-maintainers:
    - mariusvniekerk
