{% set name = "datadog" %}
{% set version = "0.37.1" %}
{% set sha256 = "564cce4d07f80008a5530418a8bbb4b6d3a7f160be3659456b6a69f66788ae56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dog = datadog.dogshell:main
    - dogwrap = datadog.dogshell.wrap:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - decorator >=3.3.2
    - requests >=2.6.0
    - simplejson >=2.0.9

test:
  imports:
    - datadog
    - datadog.dogshell
  commands:
    - dog --help
    - dogwrap --help

about:
  home: https://github.com/DataDog/datadogpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Datadog Python library

  description: |
    The Python integration enables you to monitor any custom metric by instrumenting a few lines of code.
  doc_url: https://docs.datadoghq.com/integrations/python/

extra:
  recipe-maintainers:
    - TheOriginalAlex
    - mariusvniekerk
