travis:
  secure:
    BINSTAR_TOKEN: qPwoyZXFsdelopgoeJXG6PfxSySZC1ABRoz9yPGa0IeGGLacMcPJffou8tzRsPTNpXld71g0TQF9nBSVhPP6t6+6e/ZZsObWEmdC4baeBnpUFLXpJ7sCNznpVZbyxMhA+t04EtQEZWNyLvsTUlgzROmCetwDq8sjFfgez2Y0A757aY1vCKUKsekZoYVmmunPwAO0nu8VIGdk/NiMGnyxDBQSAuub/U0geNOu5Qx4tWkQZ1s3j8JQObgpaGE0OD7X7+vNOHm3bJvZoKSdfmt8hRg1464AkYc2cb6b7cRlqjlaClpyfO607eqO66tmf7seS3MEie5e+rcSyqFfuhiadSaA7wtfJG8Y1AC6NbN9B/Zg9QCc10y5rcKanFo9Xgtb8L4aSF19lStzopyPeG/uVoWH5+SI32xhg37xp7D4BAXlZw0HM1bMIabtfkmDFEPwDiIgR2TkrzX8LdPmjZMBURfhMgXeHcohJ7In0tvt0BSUfoeVlJjOLNmX0r4iuF+HxGna5iOWWrI3/ivth7QeHog0GnGtj+WLf/cE0bEOX38duB5By6iIjPBLIE2lR9VrmzdzOxOs+RBd150DgNMY1t4eLeADb2E7iO37iX7gu09WnMkjLKLMmA9O7ragxneuodLTsTsSiFto7Y2dIr4Qh5op0cEvSOHT2es+RsRrAwk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
