travis:
  secure:
    BINSTAR_TOKEN: G1zt1SlObFQqDrfvPgKJwAG2/UN/yqF0ndsvIqiAWJ7VuVioyriAH9PbjbhQWjeuUzsSKh+kb3O9js8BmrUgzw3jw26FU94L3gjFTAyIn7uxLY8VSPNIl0dhjF4icNco6SMFrXGaZWgBH3EeGp5jgu/Iu/bO9GCkqwhkhs53oko2IeClh8t/HRtTUfNQn8+VGxohUleWjcFXfbFIHbxhhoby75Ko0tv4gvQLhDcouBfHj7bEfYdsP7qEV70e3W3mrmosJ1irwLBTc0cu3uFmLCXFEeLiM9ukV1VQRFtleIzQExgJNvmEhlCn8ZQio0zLyTdTjDURPOZrKAjtUmPQGsuyPS1iTkVVEjS/BIncecjLbfLYhlL43A6IhfnustzL4KPW7XDhnPCgnPHDJGikWN5pduzbdPPm5RSzDUoOUYr1iJ32ZVxx8GQhhguNW2+gbLYT7gmJiNxb1wzOlvVTIjtqPOmUIrf3D/EqoCtaI3oE2rGGPYdOX60s4WWvqYzbKZIZSF7cZqQi8inaww8c9S4WQPDAIJSb1xVVhV4wvjNMaDcTlKRrblN+rdJWx86h4H7wZqjLDYh7RLpKmEf3Rv4Ag8IBRvH3Ip6pgY5eDtIT6PuenVJenm4YXcIZhumLzOXHoK2iL+oDHc6WnifB3Gz5aCqvo2VOzRAeZ4RRXTA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
